#!/bin/bash
# Mở FreeJ2ME với cửa sổ chọn file game nhỏ (FileDialog)
cd /home/quan/Desktop/my-emulator/freej2me/build
exec java \
    --add-opens "java.base/java.lang=ALL-UNNAMED" \
    --add-opens "java.base/java.lang.reflect=ALL-UNNAMED" \
    --add-opens "java.base/java.util=ALL-UNNAMED" \
    --add-opens "java.base/java.io=ALL-UNNAMED" \
    -jar freej2me.jar
